apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kafka-pod-monitor-series
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      strimzi.io/cluster: kafka-cluster
      strimzi.io/kind: Kafka
      strimzi.io/name: kafka-cluster-kafka-exporter
  namespaceSelector:
    matchNames:
      - kafka
  podMetricsEndpoints:
    - port: tcp-prometheus
      path: "/metrics"
      interval: 5s
      scrapeTimeout: 4s
